//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        public Classes()
        {
            this.Registrations = new HashSet<Registration>();
            this.Waitlists = new HashSet<Waitlist>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public string Capacity { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Registration> Registrations { get; set; }
        public virtual ICollection<Waitlist> Waitlists { get; set; }
    }
}
