//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waitlist
    {
        public int WaitlistID { get; set; }
        public string StudentID { get; set; }
        public string ClassID { get; set; }
    
        public virtual Classes Class { get; set; }
        public virtual Students Student { get; set; }
    }
}
